version: '3.8'

services:
  web:
    build:
      dockerfile: docker/Dockerfile.fastapi
      context: .
    command: bash -c 'while !</dev/tcp/db/5432; do sleep 1; done; uvicorn server.app.main:app --host 0.0.0.0'
    volumes:
      - .:/server/app
    expose:
      - 8000
    environment:
      - DATABASE_URL=postgresql://${PG_USER}:${PG_PW}@db:5432/tech-hub-db
    depends_on:
      - db
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.fastapi.rule=Host(`fastapi.localhost`)"
  db:
    image: postgres:15-alpine
    container_name: tech-hub-db
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    expose:
      - 5432
    environment:
      - POSTGRES_USER=${PG_USER}
      - POSTGRES_PASSWORD=${PG_PW}
      - POSTGRES_DB=${PG_DB}
  traefik:
    image: traefik:v2.9.6
    ports:
      - 8008:80
      - 8081:8080
    volumes:
      - "./traefik.dev.toml:/etc/traefik/traefik.toml"
      - "/var/run/docker.sock:/var/run/docker.sock:ro"

volumes:
  postgres_data: