# pull the official docker image
FROM python:3.11.1-slim

# set work directory
WORKDIR server/app

# set env variables
ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

# install dependencies
COPY server/requirements-dev.txt .
RUN pip install -r requirements-dev.txt

# copy project
COPY . .